### 에러 처리

에러 처리(Error handling)은 프로그램의 에러 조건에서 응답하고 복구하는 프로세스이다.   
스위프트에서 에러를 처리하는데는 두 가지 단계가 있다.   
첫번째 단계는 ios 앱의 메서드 내에서 원하는 결과가 나오지 않을 경우에 에러를 발생(throwing)시키는 것이다.   
두번째 단계는 메서드가 발생시킨(throwing) 에러를 잡아서 처리하는 것이다.   

#### 에러 표현, 던지기

스위프트에서 발생하는 에러는 모두 `Error` 프로토콜에 준수하는 타입의 값으로 표현된다.   
열겨형을 사용하여 에러 조건들을 그룹화 할 수 있고 관련 값을 사용하여 에러의 특성에 대한 추가 정보를 전달할 수 있다.   
```swift
enum FileTranserError: Error {
    case noConnention
    case lowBandwidth
    case fileNotFound
}
```

`throw` 구문을 사용하여 에러를 발생시킬 수 있고 `throws` 키워드를 사용하여 함수나 메서드가 에러를 던질 수 있다는 것을 선언할 수 있다.   
만약 함수에 반환 타입이 있다면 반환 타입 앞에 `throws` 키워드를 적는다.   
```swift
enum FileTransferError: Error {
    case noConnection
    case lowBandwidth
    case fileNotFound
}

let connectionOK = true
let connectionSpeed = 30.00
let fileFound = false

func fileTransfer() throws {
    
    guard connectionOK else {
        throw FileTransferError.noConnection
    }
    guard connectionSpeed > 30 else {
        throw FileTransferError.lowBandwidth
    }
    guard fileFound else {
        throw FileTransferError.fileNotFound
    }
    
}
```

#### 함수, 메서드 호출

에러를 던지도록 선언된 함수나 메서드는 `try`구문이나 `do-catch`구문을 사용하여 호출한다.   
```swift
try fileTransfer()
```

```swift
func sendFile() -> String {
    
    do {
        try fileTransfer()
    } catch FileTransferError.noConnection {
        return("No Network Connection")
    } catch FileTransferError.lowBandwidth {
        return("File Transfer Speed too Low")
    } catch FileTransferError.fileNotFound {
        return("File not Found")
    } catch {
        return("unknown error")
    }
    
    return("Successful transfer")
}
```

#### 에러 전파 비활성화

`try!` 구문을 사용하면 에러 전파를 비활성화 시킬 수 있다.   
이러한 방법을 사용하는 것은 컴파일러에게 해당 메서드 호출은 어떠한 에러도 발생하지 않을 것이라고 알려주는 것과 동일하다.   
만약 에러가 발생한다면 런타임 에러가 될 것이다.
